### ISSUE TITLE
Request for added detail in README.md

### ISSUE THREAD

**Issue by aminorex** [microth/PathLSTM#1]
If you please, could you provide a downloadable reference for the other model files referenced in scripts.parse.sh?  Specifically, LEMMA_MODEL, POS_MODEL, and PARSER_MODEL.

**Comment by aminorex** [comment]
If these are best represented by https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mate-tools/CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model, https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mate-tools/CoNLL2009-ST-English-ALL.anna-3.3.postagger.model, and https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mate-tools/CoNLL2009-ST-English-ALL.anna-3.3.parser.model, respectively, an explicit comment to that effect would be appreciated, as a point of clarification.

**Comment by microth** [comment]
This is already mentioned in the README, 2nd line in section "Dependencies".

**Comment by aminorex** [comment]
Oops, thanks. 

Also you might mention the dependency on opennlp tools, and which version(s) are acceptable.  I am using 1.5.3 with reasonably good results so far.

After compiling, using those model files and anna-3.3.jar (or anna-3.61.jar) I observe what appears to be an artifact resulting from an inconsistency between the models and the library:

./scripts/parse.sh 2009/data/trial.txt 
33.50.191  is2.data.ParametersFloat 142:read ->        read parameters 134217727 not zero 296071
33.50.195  is2.data.Cluster 111:<init> ->              Read cluster with 0 words 
java.io.EOFException
    at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
    at is2.lemmatizer.Lemmatizer.readModel(Lemmatizer.java:181)
    at is2.lemmatizer.Lemmatizer.<init>(Lemmatizer.java:64)
    at se.lth.cs.srl.util.BohnetHelper.getLemmatizer(BohnetHelper.java:19)
    at se.lth.cs.srl.languages.Language.getLemmatizer(Language.java:146)
    at se.lth.cs.srl.languages.Language.getPreprocessor(Language.java:111)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:55)
    at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:133)
33.53.753  is2.data.ParametersFloat 142:read ->        read parameters 134217727 not zero 1613201
33.53.753  is2.data.Cluster 111:<init> ->              Read cluster with 0 words 
33.53.754  is2.tag.Lexicon 103:<init> ->               Read lexicon with 0 words 
33.53.755  is2.tag.Tagger 141:readModel ->             Loading data finished. 
33.53.763  is2.parser.Parser 188:readModel ->          Reading data started
33.53.784  is2.data.Cluster 111:<init> ->              Read cluster with 0 words 
33.58.38   is2.parser.ParametersFloat 101:read ->      read parameters 134217727 not zero 19957525
33.58.38   is2.parser.Parser 201:readModel ->          parsing -- li size 134217727
Exception in thread "main" java.lang.NoSuchFieldError: featureCreation
    at is2.parser.Parser.readModel(Parser.java:208)
    at is2.parser.Parser.<init>(Parser.java:71)
    at is2.parser.Parser.<init>(Parser.java:83)
    at se.lth.cs.srl.util.BohnetHelper.getParser(BohnetHelper.java:43)
    at se.lth.cs.srl.languages.Language.getPreprocessor(Language.java:117)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:55)
    at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:133)

Any suggestions or comments on this error would be much appreciated.

**Comment by microth** [comment]
Make sure you only have anna-3.3 in your classpath. Remove 3.61 or any other version, if necessary. If problem persists, contact the authors of anna-3.3. OpenNLP might be imported in some class file, but it is not used in any PathLSTM components by default.
