### ISSUE TITLE
Error running srl-ACL-2016-eng.model

### ISSUE THREAD

**Issue by danielvasic** [microth/PathLSTM#13]
Hello @microth ,
I have tried running PathLSTM but when running it seems some classes are missing, could you instruct me any further? 

```
Loading pipeline from models\srl-ACL2016-eng.model
java.lang.ClassNotFoundException: uk.ac.ed.inf.srl.features.FeatureGenerator
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at java.io.ObjectInputStream.resolveClass(Unknown Source)
        at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
        at java.io.ObjectInputStream.readClassDesc(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:192)
        at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:226)
        at se.lth.cs.srl.pipeline.Reranker.<init>(Reranker.java:63)
        at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:52)
        at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:122)
Writing corpus to out.txt...
Exception in thread "main" java.lang.NullPointerException
        at se.lth.cs.srl.pipeline.Reranker.parse(Reranker.java:96)
        at se.lth.cs.srl.SemanticRoleLabeler.parseSentence(SemanticRoleLabeler.java:12)
        at se.lth.cs.srl.CompletePipeline.parseX(CompletePipeline.java:93)
        at se.lth.cs.srl.CompletePipeline.parse(CompletePipeline.java:73)
        at se.lth.cs.srl.CompletePipeline.parseNonSegmentedLineByLine(CompletePipeline.java:165)
        at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:138)
```

I used the pre Illinois built branch because the main branch gives me:

```
[INFO] 16 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.809s
[INFO] Finished at: Sat Apr 29 18:18:38 CEST 2017
[INFO] Final Memory: 22M/346M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project PathLSTM: Compilation failure: Compilation failure:
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[6,44] package edu.illinois.cs.cogcomp.chunker.main does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[12,40] package edu.illinois.cs.cogcomp.depparse does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[16,46] package edu.illinois.cs.cogcomp.nlp.lemmatizer does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[17,35] package edu.illinois.cs.cogcomp.pos does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[6,44] package edu.illinois.cs.cogcomp.chunker.main does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[11,40] package edu.illinois.cs.cogcomp.depparse does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[12,46] package edu.illinois.cs.cogcomp.nlp.lemmatizer does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[13,35] package edu.illinois.cs.cogcomp.pos does not exist
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[44,37] cannot find symbol
[ERROR] symbol:   class POSAnnotator
[ERROR] location: class se.lth.cs.srl.pipeline.LBJavaArgumentClassifier
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[45,39] cannot find symbol
[ERROR] symbol:   class IllinoisLemmatizer
[ERROR] location: class se.lth.cs.srl.pipeline.LBJavaArgumentClassifier
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[46,39] cannot find symbol
[ERROR] symbol:   class ChunkerAnnotator
[ERROR] location: class se.lth.cs.srl.pipeline.LBJavaArgumentClassifier
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/pipeline/LBJavaArgumentClassifier.java:[47,40] cannot find symbol
[ERROR] symbol:   class DepAnnotator
[ERROR] location: class se.lth.cs.srl.pipeline.LBJavaArgumentClassifier
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[28,30] cannot find symbol
[ERROR] symbol:   class DepAnnotator
[ERROR] location: class se.lth.cs.srl.preprocessor.IllinoisPreprocessor
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[29,27] cannot find symbol
[ERROR] symbol:   class POSAnnotator
[ERROR] location: class se.lth.cs.srl.preprocessor.IllinoisPreprocessor
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[30,29] cannot find symbol
[ERROR] symbol:   class IllinoisLemmatizer
[ERROR] location: class se.lth.cs.srl.preprocessor.IllinoisPreprocessor
[ERROR] /C:/Users/Daniel/Desktop/PathLSTM-master/src/main/java/se/lth/cs/srl/preprocessor/IllinoisPreprocessor.java:[31,29] cannot find symbol
[ERROR] symbol:   class ChunkerAnnotator
[ERROR] location: class se.lth.cs.srl.preprocessor.IllinoisPreprocessor
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Best regards,
Daniel

**Comment by microth** [comment]
Hi Daniel,

Sorry, I mixed up two model files two weeks ago and changed the name of the feature package as a result of that mistake. The error should be fixed now.

Cheers,
Michael
