### ISSUE TITLE
Error running PathLSTM, LibLinear model throws null Exception

### ISSUE THREAD

**Issue by danielvasic** [microth/PathLSTM#19]
Hello Mike,
I have trouble with parse method when model is loaded, it throws null pointer wxception in LibLinearModel.java on line 43, here is my stack trace:

```
`java.lang.NullPointerException
        at uk.ac.ed.inf.srl.ml.liblinear.LibLinearModel.classify(LibLinearModel.
java:48)
        at se.lth.cs.srl.pipeline.ArgumentStep.classifyInstance(ArgumentStep.jav
a:143)
        at se.lth.cs.srl.pipeline.ArgumentIdentifier.parse(ArgumentIdentifier.ja
va:43)
        at se.lth.cs.srl.pipeline.Pipeline.parse(Pipeline.java:104)
        at se.lth.cs.srl.SemanticRoleLabeler.parseSentence(SemanticRoleLabeler.j
ava:12)
        at se.lth.cs.srl.CompletePipeline.parse(CompletePipeline.java:79)
        at scroll.mate.MateAnnotations.parse(MateAnnotations.java:36)`
```

Thanks in advance,
Daniel

**Comment by microth** [comment]
What does your command line input look like? You might be missing the parameter "-externalNNs", which causes the system to call a logistic regression classifier instead of the neural network model.

**Comment by danielvasic** [comment]
Thank you Mike, I added this parameter and it works now :-) 👍
